// flow-typed signature: 55ba05b6f5a4c339ad777ef138663118
// flow-typed version: <<STUB>>/event-source-polyfill_v0.0.9/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-source-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-source-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-source-polyfill/eventsource' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/eventsource.min' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/Gruntfile' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/tests/eventsource' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/tests/nodechat' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/tests/qunit' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/tests/server' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/tests/stop' {
  declare module.exports: any;
}

declare module 'event-source-polyfill/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-source-polyfill/eventsource.js' {
  declare module.exports: $Exports<'event-source-polyfill/eventsource'>;
}
declare module 'event-source-polyfill/eventsource.min.js' {
  declare module.exports: $Exports<'event-source-polyfill/eventsource.min'>;
}
declare module 'event-source-polyfill/Gruntfile.js' {
  declare module.exports: $Exports<'event-source-polyfill/Gruntfile'>;
}
declare module 'event-source-polyfill/tests/eventsource.js' {
  declare module.exports: $Exports<'event-source-polyfill/tests/eventsource'>;
}
declare module 'event-source-polyfill/tests/nodechat.js' {
  declare module.exports: $Exports<'event-source-polyfill/tests/nodechat'>;
}
declare module 'event-source-polyfill/tests/qunit.js' {
  declare module.exports: $Exports<'event-source-polyfill/tests/qunit'>;
}
declare module 'event-source-polyfill/tests/server.js' {
  declare module.exports: $Exports<'event-source-polyfill/tests/server'>;
}
declare module 'event-source-polyfill/tests/stop.js' {
  declare module.exports: $Exports<'event-source-polyfill/tests/stop'>;
}
declare module 'event-source-polyfill/tests/tests.js' {
  declare module.exports: $Exports<'event-source-polyfill/tests/tests'>;
}
