// flow-typed signature: 5b7326394f8e131f90fa9f19eff9900a
// flow-typed version: <<STUB>>/hover.css_v2.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hover.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hover.css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hover.css/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hover.css/Gruntfile.js' {
  declare module.exports: $Exports<'hover.css/Gruntfile'>;
}
