// flow-typed signature: e733ef16ece8e34054eda7a4227e2cc2
// flow-typed version: <<STUB>>/json-stringify-safe_v5.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-stringify-safe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-stringify-safe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-stringify-safe/stringify' {
  declare module.exports: any;
}

declare module 'json-stringify-safe/test/stringify_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-stringify-safe/stringify.js' {
  declare module.exports: $Exports<'json-stringify-safe/stringify'>;
}
declare module 'json-stringify-safe/test/stringify_test.js' {
  declare module.exports: $Exports<'json-stringify-safe/test/stringify_test'>;
}
