// flow-typed signature: 089f7be5fb0e7badc1038d05071528a5
// flow-typed version: <<STUB>>/print-error_v0.1.11/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'print-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'print-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'print-error/build/helpers' {
  declare module.exports: any;
}

declare module 'print-error/build/html' {
  declare module.exports: any;
}

declare module 'print-error/build/markdown' {
  declare module.exports: any;
}

declare module 'print-error/build/parse' {
  declare module.exports: any;
}

declare module 'print-error/build/terminal' {
  declare module.exports: any;
}

declare module 'print-error/build/text' {
  declare module.exports: any;
}

declare module 'print-error/index.es6' {
  declare module.exports: any;
}

declare module 'print-error/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'print-error/build/helpers.js' {
  declare module.exports: $Exports<'print-error/build/helpers'>;
}
declare module 'print-error/build/html.js' {
  declare module.exports: $Exports<'print-error/build/html'>;
}
declare module 'print-error/build/markdown.js' {
  declare module.exports: $Exports<'print-error/build/markdown'>;
}
declare module 'print-error/build/parse.js' {
  declare module.exports: $Exports<'print-error/build/parse'>;
}
declare module 'print-error/build/terminal.js' {
  declare module.exports: $Exports<'print-error/build/terminal'>;
}
declare module 'print-error/build/text.js' {
  declare module.exports: $Exports<'print-error/build/text'>;
}
declare module 'print-error/index.es6.js' {
  declare module.exports: $Exports<'print-error/index.es6'>;
}
declare module 'print-error/index.umd.js' {
  declare module.exports: $Exports<'print-error/index.umd'>;
}
