// flow-typed signature: 6eed2675aa6530db458661e68c9af5bc
// flow-typed version: <<STUB>>/react-image-magnify_v1.7.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-magnify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-magnify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-magnify/dist/EnlargedImage' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/ImageShape' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/index' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/Lens' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/LensBottom' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/LensLeft' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/LensRight' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/LensTop' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/ReactImageMagnify' {
  declare module.exports: any;
}

declare module 'react-image-magnify/dist/ReactImageMagnifyTouch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-magnify/dist/EnlargedImage.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/EnlargedImage'>;
}
declare module 'react-image-magnify/dist/ImageShape.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/ImageShape'>;
}
declare module 'react-image-magnify/dist/index.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/index'>;
}
declare module 'react-image-magnify/dist/Lens.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/Lens'>;
}
declare module 'react-image-magnify/dist/LensBottom.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/LensBottom'>;
}
declare module 'react-image-magnify/dist/LensLeft.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/LensLeft'>;
}
declare module 'react-image-magnify/dist/LensRight.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/LensRight'>;
}
declare module 'react-image-magnify/dist/LensTop.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/LensTop'>;
}
declare module 'react-image-magnify/dist/ReactImageMagnify.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/ReactImageMagnify'>;
}
declare module 'react-image-magnify/dist/ReactImageMagnifyTouch.js' {
  declare module.exports: $Exports<'react-image-magnify/dist/ReactImageMagnifyTouch'>;
}
