// flow-typed signature: 0b451d3e9cdc297b897df6ac400d4261
// flow-typed version: <<STUB>>/react-facebook_v4.0.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook/__tests__/share' {
  declare module.exports: any;
}

declare module 'react-facebook/gulpfile' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Comments' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/CommentsCount' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/ColorScheme' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/CommentsOrderBy' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeAction' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeLayout' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/constants/LikeSize' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/EmbeddedPost' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Facebook' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/FacebookProvider' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Feed' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/index' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/InitFacebook' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Like' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Login' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/LoginButton' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Page' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Parser' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Process' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/Share' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/ShareButton' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/utils/clearUndefinedProperties' {
  declare module.exports: any;
}

declare module 'react-facebook/lib/utils/getCurrentHref' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook/__tests__/share.jsx' {
  declare module.exports: $Exports<'react-facebook/__tests__/share'>;
}
declare module 'react-facebook/gulpfile.js' {
  declare module.exports: $Exports<'react-facebook/gulpfile'>;
}
declare module 'react-facebook/lib/Comments.js' {
  declare module.exports: $Exports<'react-facebook/lib/Comments'>;
}
declare module 'react-facebook/lib/CommentsCount.js' {
  declare module.exports: $Exports<'react-facebook/lib/CommentsCount'>;
}
declare module 'react-facebook/lib/constants/ColorScheme.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/ColorScheme'>;
}
declare module 'react-facebook/lib/constants/CommentsOrderBy.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/CommentsOrderBy'>;
}
declare module 'react-facebook/lib/constants/LikeAction.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeAction'>;
}
declare module 'react-facebook/lib/constants/LikeLayout.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeLayout'>;
}
declare module 'react-facebook/lib/constants/LikeSize.js' {
  declare module.exports: $Exports<'react-facebook/lib/constants/LikeSize'>;
}
declare module 'react-facebook/lib/EmbeddedPost.js' {
  declare module.exports: $Exports<'react-facebook/lib/EmbeddedPost'>;
}
declare module 'react-facebook/lib/Facebook.js' {
  declare module.exports: $Exports<'react-facebook/lib/Facebook'>;
}
declare module 'react-facebook/lib/FacebookProvider.js' {
  declare module.exports: $Exports<'react-facebook/lib/FacebookProvider'>;
}
declare module 'react-facebook/lib/Feed.js' {
  declare module.exports: $Exports<'react-facebook/lib/Feed'>;
}
declare module 'react-facebook/lib/index.js' {
  declare module.exports: $Exports<'react-facebook/lib/index'>;
}
declare module 'react-facebook/lib/InitFacebook.js' {
  declare module.exports: $Exports<'react-facebook/lib/InitFacebook'>;
}
declare module 'react-facebook/lib/Like.js' {
  declare module.exports: $Exports<'react-facebook/lib/Like'>;
}
declare module 'react-facebook/lib/Login.js' {
  declare module.exports: $Exports<'react-facebook/lib/Login'>;
}
declare module 'react-facebook/lib/LoginButton.js' {
  declare module.exports: $Exports<'react-facebook/lib/LoginButton'>;
}
declare module 'react-facebook/lib/Page.js' {
  declare module.exports: $Exports<'react-facebook/lib/Page'>;
}
declare module 'react-facebook/lib/Parser.js' {
  declare module.exports: $Exports<'react-facebook/lib/Parser'>;
}
declare module 'react-facebook/lib/Process.js' {
  declare module.exports: $Exports<'react-facebook/lib/Process'>;
}
declare module 'react-facebook/lib/Share.js' {
  declare module.exports: $Exports<'react-facebook/lib/Share'>;
}
declare module 'react-facebook/lib/ShareButton.js' {
  declare module.exports: $Exports<'react-facebook/lib/ShareButton'>;
}
declare module 'react-facebook/lib/utils/clearUndefinedProperties.js' {
  declare module.exports: $Exports<'react-facebook/lib/utils/clearUndefinedProperties'>;
}
declare module 'react-facebook/lib/utils/getCurrentHref.js' {
  declare module.exports: $Exports<'react-facebook/lib/utils/getCurrentHref'>;
}
