// flow-typed signature: e889df61b3b4fe1b5bda26cd2f4c5a73
// flow-typed version: <<STUB>>/svg-react-loader_v0.3.7/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-react-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-react-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-react-loader/helpers' {
  declare module.exports: any;
}

declare module 'svg-react-loader/utility/get-name' {
  declare module.exports: any;
}

declare module 'svg-react-loader/utility/sanitize' {
  declare module.exports: any;
}

declare module 'svg-react-loader/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-react-loader/helpers.js' {
  declare module.exports: $Exports<'svg-react-loader/helpers'>;
}
declare module 'svg-react-loader/index' {
  declare module.exports: $Exports<'svg-react-loader'>;
}
declare module 'svg-react-loader/index.js' {
  declare module.exports: $Exports<'svg-react-loader'>;
}
declare module 'svg-react-loader/utility/get-name.js' {
  declare module.exports: $Exports<'svg-react-loader/utility/get-name'>;
}
declare module 'svg-react-loader/utility/sanitize.js' {
  declare module.exports: $Exports<'svg-react-loader/utility/sanitize'>;
}
declare module 'svg-react-loader/webpack.config.js' {
  declare module.exports: $Exports<'svg-react-loader/webpack.config'>;
}
