// flow-typed signature: aff0d474727277cee2955de45780f9ae
// flow-typed version: <<STUB>>/universal-webpack_v0.3.9/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-webpack/bin/universal-webpack' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/babel-register' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/chunks plugin' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/chunks' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/client configuration' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/devtools' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/helpers' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/loaders' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/output webpack stats' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/prepare' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/server configuration' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/server' {
  declare module.exports: any;
}

declare module 'universal-webpack/build/wait for file' {
  declare module.exports: any;
}

declare module 'universal-webpack/config' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/babel-register' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/chunks plugin' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/chunks' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/client configuration' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/devtools' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/helpers' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/loaders' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/output webpack stats' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/prepare' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/server configuration' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/server' {
  declare module.exports: any;
}

declare module 'universal-webpack/es6/wait for file' {
  declare module.exports: any;
}

declare module 'universal-webpack/index.common' {
  declare module.exports: any;
}

declare module 'universal-webpack/index.es6' {
  declare module.exports: any;
}

declare module 'universal-webpack/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-webpack/bin/universal-webpack.js' {
  declare module.exports: $Exports<'universal-webpack/bin/universal-webpack'>;
}
declare module 'universal-webpack/build/babel-register.js' {
  declare module.exports: $Exports<'universal-webpack/build/babel-register'>;
}
declare module 'universal-webpack/build/chunks plugin.js' {
  declare module.exports: $Exports<'universal-webpack/build/chunks plugin'>;
}
declare module 'universal-webpack/build/chunks.js' {
  declare module.exports: $Exports<'universal-webpack/build/chunks'>;
}
declare module 'universal-webpack/build/client configuration.js' {
  declare module.exports: $Exports<'universal-webpack/build/client configuration'>;
}
declare module 'universal-webpack/build/devtools.js' {
  declare module.exports: $Exports<'universal-webpack/build/devtools'>;
}
declare module 'universal-webpack/build/helpers.js' {
  declare module.exports: $Exports<'universal-webpack/build/helpers'>;
}
declare module 'universal-webpack/build/loaders.js' {
  declare module.exports: $Exports<'universal-webpack/build/loaders'>;
}
declare module 'universal-webpack/build/output webpack stats.js' {
  declare module.exports: $Exports<'universal-webpack/build/output webpack stats'>;
}
declare module 'universal-webpack/build/prepare.js' {
  declare module.exports: $Exports<'universal-webpack/build/prepare'>;
}
declare module 'universal-webpack/build/server configuration.js' {
  declare module.exports: $Exports<'universal-webpack/build/server configuration'>;
}
declare module 'universal-webpack/build/server.js' {
  declare module.exports: $Exports<'universal-webpack/build/server'>;
}
declare module 'universal-webpack/build/wait for file.js' {
  declare module.exports: $Exports<'universal-webpack/build/wait for file'>;
}
declare module 'universal-webpack/config.js' {
  declare module.exports: $Exports<'universal-webpack/config'>;
}
declare module 'universal-webpack/es6/babel-register.js' {
  declare module.exports: $Exports<'universal-webpack/es6/babel-register'>;
}
declare module 'universal-webpack/es6/chunks plugin.js' {
  declare module.exports: $Exports<'universal-webpack/es6/chunks plugin'>;
}
declare module 'universal-webpack/es6/chunks.js' {
  declare module.exports: $Exports<'universal-webpack/es6/chunks'>;
}
declare module 'universal-webpack/es6/client configuration.js' {
  declare module.exports: $Exports<'universal-webpack/es6/client configuration'>;
}
declare module 'universal-webpack/es6/devtools.js' {
  declare module.exports: $Exports<'universal-webpack/es6/devtools'>;
}
declare module 'universal-webpack/es6/helpers.js' {
  declare module.exports: $Exports<'universal-webpack/es6/helpers'>;
}
declare module 'universal-webpack/es6/loaders.js' {
  declare module.exports: $Exports<'universal-webpack/es6/loaders'>;
}
declare module 'universal-webpack/es6/output webpack stats.js' {
  declare module.exports: $Exports<'universal-webpack/es6/output webpack stats'>;
}
declare module 'universal-webpack/es6/prepare.js' {
  declare module.exports: $Exports<'universal-webpack/es6/prepare'>;
}
declare module 'universal-webpack/es6/server configuration.js' {
  declare module.exports: $Exports<'universal-webpack/es6/server configuration'>;
}
declare module 'universal-webpack/es6/server.js' {
  declare module.exports: $Exports<'universal-webpack/es6/server'>;
}
declare module 'universal-webpack/es6/wait for file.js' {
  declare module.exports: $Exports<'universal-webpack/es6/wait for file'>;
}
declare module 'universal-webpack/index.common.js' {
  declare module.exports: $Exports<'universal-webpack/index.common'>;
}
declare module 'universal-webpack/index.es6.js' {
  declare module.exports: $Exports<'universal-webpack/index.es6'>;
}
declare module 'universal-webpack/server.js' {
  declare module.exports: $Exports<'universal-webpack/server'>;
}
